name: Build and Release Wheels

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0.0
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Build wheels
        run: |
          pip install maturin
          maturin build --release --out dist
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*.whl

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating releases
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*.whl
          generate_release_notes: true
          draft: false
          prerelease: false
